baseURL: 'https://mdubiel.github.io/'
theme: "xmin"
copyright: "Copyright © 2025, Mateusz Dubiel."
defaultContentLanguage: "en"
title: "mdubiel, it engineer portfolio & developer journal"

# Generate a nice robots.txt for SEO
enableRobotsTXT: true
enableInlineShortcodes: true
footnoteReturnLinkContents: "^"
### xmin
googleAnalytics: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents:  "↩"
enableGitInfo: true
params:
  description: "A website built through Hugo."
  footer: "&copy; [Mateusz Dubiel](https://mdubiel.github.io/) 2024 -- {Year} | [Github](https://github.com/mdubiel)"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: home
      url: ""
      weight: 1
    - name: about
      url: "about/"
      weight: 2
    - name: journal
      url: "journal/introduction/"
      weight: 2
#     - name: Categories
#       url: "categories/"
#       weight: 3
#     - name: Tags
#       url: "tags/"
#       weight: 4
#     - name: Subscribe
#       url: "index.xml"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
